apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: olivercw/webserver
        name: webserver
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: server-config
        resources: {}
